version: 0.0
os: linux
files:
  - source: ./
    destination: /etc/app/doesangue
hooks:
  BeforeInstall:
    - location: clean.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: start_server.sh
      timeout: 300
      runas: root